#ifndef PARSER_H
#define PARSER_H

#include <memory>
#include "ast.h"

// The root of the Abstract Syntax Tree after parsing.
// This will be assigned by the parser (see parser.y)
extern std::shared_ptr<ASTNode> root;

// The parser function generated by Bison
int yyparse();

#endif // PARSER_H
